### ISSUE TITLE
Possible issue with domain-joined FS or version 5.4

### ISSUE THREAD

**Issue by burnout-champion** [FroggDev/zabbix-smb#6]
Hello,

I am having some issues with monitoring my SMB shares and I would like some assistance if possible, I think there might be a bug or some extra parameters needed when dealing with domain joined fileserver shares. 

I have a fileserver on a windows domain - for example mycompanyfs1.company.com is the file server joined to the mycompany.com domain. That fileserver has a single SMB share that needs no login (everyone has read), which is the one I need to monitor. That is reached by the users by \\mycompanyfs1.mycompany.com\fileshare1.

I tried to put in the macros fileshare1 as the share with fileshare1+r as the right, but I get errors for both. I also tried including a domain user, changing the +r/+w or omitting in completely, verified I see no related errors on the /var/log/zabbix/zabbix_server.log and every single time in between I unlinked and cleared the template to have fresh data. I am guessing I need to add something somewhere but I have no idea what or how, so any help would be appreciated!

I am running Zabbix 5.4.3 server & agent, mentioning this due to not being included in the tested versions.

Thank you in advance for your time!

**Comment by FroggDev** [comment]
Hi there,

Can you send me the result of the following commands (launched on zabbix server)

`./frogg_smb_check.sh right mycompanyfs1.mycompany.com "fileshare1+r"`

`./frogg_smb_check.sh share mycompanyfs1.mycompany.com "fileshare1"`

thoose comands will do what zabbix does when he is checking the template.
If the result is empty, it means all worked as intend, else the share the script can't access or doesnt match the rights you asked will appear.

Another thing, zabbix server must be able to communicate with  mycompanyfs1.mycompany.com to be able to check if share are available over the network

Best Regards

**Comment by burnout-champion** [comment]
Hi and thanks for your quick reply!

As far as I can tell the script only parses the inputs, for example I re-run it with the word “random” in it and I got similar results:


***@***.***:~$ cd /usr/lib/zabbix/externalscripts
***@***.***:/usr/lib/zabbix/externalscripts$ ./frogg_smb_check.sh right xxx.xxx.xxx.xxx "fileshare+r"
[heronfiles|anonymous+r]
***@***.***:/usr/lib/zabbix/externalscripts$ ./frogg_smb_check.sh share  xxx.xxx.xxx.xxx "fileshare"
[heronfiles]
***@***.***:/usr/lib/zabbix/externalscripts$ ./frogg_smb_check.sh right xxx.xxx.xxx.xxx "filesharerandom+r"
[heronfilesrandom|anonymous+r]
***@***.***:/usr/lib/zabbix/externalscripts$ ./frogg_smb_check.sh share  xxx.xxx.xxx.xxx "filesharerandom"
[heronfilesrandom]
***@***.***:/usr/lib/zabbix/externalscripts$


PS the Zabbix server is able to communicate with the fileserver as I am monitoring it via agent over port 10050 with no issues so far.


Best regards,
Mike

**Comment by FroggDev** [comment]
Actually the script say that the share heronfilesrandom & heronfiles doesn't exist and doesn't have the rights to read for anonymous  user (as it dosent exist)

can you try the command 

`smbclient -L {server_ip} -g -N -U zabbix`

It is the command used to retrive the list of the serveur share

**Comment by burnout-champion** [comment]
Hi again,

It didn’t work, but this did:

smbclient -L xxx.xxx.xxx.xxx -g -U ***@***.******@***.***> which is a test user I created for such instances.

It prompted for a password and after inputting it, it gave me a list of the shares on the server!

***@***.***:/usr/lib/zabbix/externalscripts$ smbclient -L xxx.xxx.xxx.xxx -g -U ***@***.******@***.***>
Enter ***@***.******@***.***'s> password:
Disk|ADMIN$|Remote Admin
Disk|C$|Default share
Disk|F$|Default share
Disk|HeronFiles|
IPC|IPC$|Remote IPC
Disk|SWinstall|
Disk|USERS|
SMB1 disabled -- no workgroup available

Best regards,
Mike.

**Comment by FroggDev** [comment]
Ok that mean i have to update the script to take login/pass able to read shares from the macro 

In fact the smb server can allow anonymous user to read the list of shares even if it cannot enter it, but that s not the case for you.

You can temporraly change in the script
```smbclient -L $1 -g -N -U zabbix```
by
```smbclient -L $1 -g -N -U {your user}%{yourpassword}```
To have it works, while i am adding the new functionnality

**Comment by burnout-champion** [comment]
Hi again.

I changed the line you mentioned to add my username and password – and I verified that line works standalone in CLI as it gives me a list of the share.

I then re-linked the template, put the share name in the macro and on the rights field I put the share with ***@***.******@***.***:password+r>.

After that, the share check is working 100%, but the rights gives me an output of “1” that triggers an error:

***@***.***

And on the check history:

***@***.***


And the trigger test for value of “1”:

***@***.***

Is “1” supposed to be the correct value for when access is allowed? If so I can just change the trigger to “fix” the check.


Once again, thanks a lot for your time, you have been amazingly helpful!


Best regards,
Mike

**Comment by burnout-champion** [comment]
Sorry, my bad I had misspelt something on the macro, it works perfectly fine now!

I get blank outputs for both checks and nothing is triggered.

PS other than the smbclient extra field to connect for domain fileservers that you mentioned, your template is now tested on Zabbix 5.4.3 and works flawlessly – so you can add that not on your work as well.


Thanks again for everything!




From: Michalis Douros
Sent: Friday, August 6, 2021 4:49 PM
To: FroggDev/zabbix-smb ***@***.***>; FroggDev/zabbix-smb ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [FroggDev/zabbix-smb] Possible issue with domain-joined FS or version 5.4 (#6)

Hi again.

I changed the line you mentioned to add my username and password – and I verified that line works standalone in CLI as it gives me a list of the share.

I then re-linked the template, put the share name in the macro and on the rights field I put the share with ***@***.******@***.***:password+r>.

After that, the share check is working 100%, but the rights gives me an output of “1” that triggers an error:

***@***.***

And on the check history:

***@***.***


And the trigger test for value of “1”:

***@***.***

Is “1” supposed to be the correct value for when access is allowed? If so I can just change the trigger to “fix” the check.


Once again, thanks a lot for your time, you have been amazingly helpful!


Best regards,
Mike

**Comment by FroggDev** [comment]
Thanks for your feedback !

I ll try to update the template soon to manage the share account option in Macros

Have a good week end ^_^
