### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nigelhorne** [FroggDev/zabbix-smb#7]
Clicking on "Exemple [sic]: Zabbix SMB configuration sample" gives:

"Error Fetching Resource"

**Comment by nigelhorne** [comment]
Also clicking on "Zabbix SMB Template triggers"

**Comment by FroggDev** [comment]
Hi,
i am sorry, thoose files are stored on my home server, and i am experiencing some connexion trouble.
The internet provider cable  has been accidentally cut by the town hall gardener, so i have to wait for it.

**Comment by FroggDev** [comment]
Hi,

My internet is back, images are back, i am closing.

Thanks for reporting the trouble !

Best regards.
